let
    Source = Csv.Document(File.Contents(DataFolder & "\export\AWS_Daily_Costs.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    BlankToNull = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    #"Changed Type" = Table.TransformColumnTypes(BlankToNull, {{"code", type text}, {"Default_Configurations.data.cost_type", type text}, {"Group By Code", type text}, {"date", type date}, {"Name", type text}, {"values.date", type date}, {"values.source_uuid", type text}, {"values.account_alias", type text}, {"values.infrastructure.raw.value", type number}, {"values.infrastructure.raw.units", type text}, {"values.infrastructure.markup.value", type number}, {"values.infrastructure.markup.units", type text}, {"values.infrastructure.usage.value", Int64.Type}, {"values.infrastructure.usage.units", type text}, {"values.infrastructure.total.value", type number}, {"values.infrastructure.total.units", type text}, {"values.supplementary.raw.value", Int64.Type}, {"values.supplementary.raw.units", type text}, {"values.supplementary.markup.value", Int64.Type}, {"values.supplementary.markup.units", type text}, {"values.supplementary.usage.value", Int64.Type}, {"values.supplementary.usage.units", type text}, {"values.supplementary.total.value", Int64.Type}, {"values.supplementary.total.units", type text}, {"values.cost.raw.value", type number}, {"values.cost.raw.units", type text}, {"values.cost.markup.value", type number}, {"values.cost.markup.units", type text}, {"values.cost.usage.value", Int64.Type}, {"values.cost.usage.units", type text}, {"values.cost.total.value", type number}, {"values.cost.total.units", type text}, {"key", type any}, {"type", type any}, {"values.alias", type any}}),
    #"Added Filter Month" = Table.AddColumn(#"Changed Type", "Filter Month", each if [date] = null then null else Number.ToText(Date.Year([date])) & "-" & Number.ToText(Date.Month([date]))),
    #"Renamed Columns" = Table.RenameColumns(#"Added Filter Month", {{"values.account_alias", "_Account_Alias"}, {"values.alias", "_Org_Acc_Alias"}})
in
    #"Renamed Columns"
