let
    Source = Csv.Document(File.Contents(DataFolder & "\export\OS_Costs_Daily.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    BlankToNull = Table.ReplaceValue(Promoted, "", null, Replacer.ReplaceValue, Table.ColumnNames(Promoted)),
    #"Changed Type" = Table.TransformColumnTypes(BlankToNull, {{"code", type text}, {"Group By Code", type text}, {"meta.distributed_overhead", type logical}, {"date", type date}, {"Name", type text}, {"values.date", type date}, {"values.classification", type text}, {"values.source_uuid", type text}, {"values.clusters", type text}, {"values.infrastructure.raw.value", type number}, {"values.infrastructure.raw.units", type text}, {"values.infrastructure.markup.value", type number}, {"values.infrastructure.markup.units", type text}, {"values.infrastructure.usage.value", type number}, {"values.infrastructure.usage.units", type text}, {"values.infrastructure.total.value", type number}, {"values.infrastructure.total.units", type text}, {"values.supplementary.raw.value", Int64.Type}, {"values.supplementary.raw.units", type text}, {"values.supplementary.markup.value", Int64.Type}, {"values.supplementary.markup.units", type text}, {"values.supplementary.usage.value", type number}, {"values.supplementary.usage.units", type text}, {"values.supplementary.total.value", type number}, {"values.supplementary.total.units", type text}, {"values.cost.raw.value", type number}, {"values.cost.raw.units", type text}, {"values.cost.markup.value", type number}, {"values.cost.markup.units", type text}, {"values.cost.usage.value", type number}, {"values.cost.usage.units", type text}, {"values.cost.platform_distributed.value", type number}, {"values.cost.platform_distributed.units", type text}, {"values.cost.worker_unallocated_distributed.value", type number}, {"values.cost.worker_unallocated_distributed.units", type text}, {"values.cost.distributed.value", type number}, {"values.cost.distributed.units", type text}, {"values.cost.total.value", type number}, {"values.cost.total.units", type text}, {"values.delta_percent", type any}, {"key", type any}, {"values.delta_value", type any}}),
    #"Added Filter Month" = Table.AddColumn(#"Changed Type", "Filter Month", each if [date] = null then null else Number.ToText(Date.Year([date])) & "-" & Number.ToText(Date.Month([date]))),
    #"Added Conditional Column" = Table.AddColumn(#"Added Filter Month", "Platform Classification", each if [values.classification] = "default" then "Yes" else if [Name] = "Platform unallocated" then "Yes" else "No"),
    #"Filtered Out Projects with no classification" = Table.SelectRows(#"Added Conditional Column", each (([Group By Code] = "project" and [values.classification] <> null) or ([Group By Code] <> "project")))
in
    #"Filtered Out Projects with no classification"
